### PR TITLE
migrate plugin and add compiling java version

### PR DESCRIPTION
**Pull request by civitaspo**
Hi @llibra !

- just execute `embulk migrate embulk-output-s3`
- add compiling java version to build.gradle
  - embulk officially supports java 7.
  - ref. http://qiita.com/hiroysato/items/7b5f77c6ef752c4cd9ca

### CODE REVIEW

**Comment by toyama0919** [comment]
LGTM.
This plugin works java8 only.

**Comment by civitaspo** [comment]
So, is it better to divide the pull-request to the migration and the restriction of java version?
And, if you don't mind, tell me the reason why this plugin does work only on java8. It is because this is embulk plugin so I think this should follow the embulk development style(but there is not the formal document...), and because actually it works when I compile on java7.

**Comment by llibra** [comment]
Merged. Thanks!

**Comment by civitaspo** [comment]
thx!!!! @llibra

**Pull request merged**
